apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
        - name: rehub-microservice
          image: itpat/rehub-microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

